services:
  preach-database:
    image: postgres
    container_name: database_preach
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=preach
      - POSTGRES_PASSWORD=preach123
      - POSTGRES_DB=preachdb
    volumes:
      - pgdata:/data/postgres

  preach-service:
    build: .
    container_name: service_preach
    hostname: preach-service
    restart: always
    env_file:
      - .env.dev
    ports:
      - 3333:3333
      - 9229:9299
    volumes:
      - ./src:/usr/app/src
      - ./prisma:/usr/app/prisma
    depends_on:
      - preach-database
    command: yarn dev

volumes:
  pgdata:
